### ISSUE TITLE
tdist[org] = ‘-‘

### ISSUE THREAD

**Issue by breakthewall** [pablocarb/selenzy#2]
Hi Pablo,

I have a problem when I run selenzy. I fall in the case where `tdist[org] = ‘-‘` in `Selenzy.py` (l. 958, see attached pic), then when `sortrows` is called and try to sort by casting into a `float` (l. 667, see attached pic), then fall into l. 669 and finally failed by saying that it cannot compares `str` and `int`.

If the modification is simple, I can do it for you and then make a pull request.

Below, you will find the output of the program of the two last iterations before crash where I print `key-1, row` on one line and `float(row[key-1])` or `row[key-1]` on a second line:

```
3 ('Q05185', '4;5-dihydroxyphthalate decarboxylase', 'Pseudomonas putida ', 11, 'MNXR7053', '4.1.1.55', '2', 0.0, 0.5722, '-1', '0', '31.4', '30.2', '23.6', '21.5', '28580.48', '6.6376', '42.248', '[H]OC(=O)C([H])=C([H])c1c([H])c([H])c([H])c([H])c1[H].[H+]>>O=C=O.[H]C([H])=C([H])c1c([H])c([H])c([H])c([H])c1[H]', '[H+].O=C(O)c1cc([O-])c([O-])cc1C(=O)O>>O=C=O.O=C(O)c1ccc([O-])c(O)c1')
11.0

3 ('P0CT50', 'Salicylate decarboxylase', 'Trichosporon moniliiforme ', '-', 'MNXR9317', '4.1.1.91', '1', 0.0, 0.57739, '-1', '-1', '44.6', '16.5', '23.1', '20.7', '39961.10', '5.5694', '44.000', '[H]OC(=O)C([H])=C([H])c1c([H])c([H])c([H])c([H])c1[H].[H+]>>O=C=O.[H]C([H])=C([H])c1c([H])c([H])c([H])c([H])c1[H]', '[H+].O=C(O)c1ccccc1[O-]>>O=C=O.Oc1ccccc1')
-

```
![Image 01-10-2021 à 11 38](https://user-images.githubusercontent.com/28150216/135601096-c7bc7d61-2fb9-446d-a3e0-eeb3b23c89ed.jpg)
![Image 01-10-2021 à 11 45](https://user-images.githubusercontent.com/28150216/135601208-ac996e6b-bec3-4d56-aca2-952d6e14bba3.jpg)

**Comment by pablocarb** [comment]
Hi @breakthewall, this issue is due to some organism that is missing in the taxonomy, probably because of some inconsistency in the data. The quick fix was to assign '-' to the taxonomic distance. But this is not working for sorting based on distance. In order to be safe, I think that we can make a couple of places. 

First on line 958:

```python
           if org not in tdist:
                if y in seqorg:
                    tdist[org] = taxDistance(tax, host, seqorg[y][0])
                else:
                   tdist[org] = taxDistance(tax, host, '-') # no clue about the target
```

Second, on the taxDistance definition:

```python
def taxDistance(tax, host, target):
    if host not in tax:
        return 100 # no host, no clue
    else:
        hostLineage = set(tax[host])
    if target not in tax:
        distance = 1 + 2*len(hostLineage)
    else:
        targetLineage = set(tax[target])
        distance = 1 + len(hostLineage ^ targetLineage)
    return distance
```

**Comment by breakthewall** [comment]
Thank you Pablo for your prompt reply.

I made changes and the code of selenzy ran well.

However, when I apply the filter a posteriori to only get IDs with negative taxonomic distances, the job is stopped because at some point the value `row[f'{taxonID}_target_host_dist']` is equal to '-' which is not a float and thus not comparable with 0 (`row` is read from `new.csv` file DataFrame.

Thanks

**Comment by pablocarb** [comment]
This might be because of a special case in `Selenzy2` where no information is found. As did for `Selenzy´, we might just ignore those cases by assigning a large distance, i.e. 100.

Please try to replace in `Selenzy2`:

![image](https://user-images.githubusercontent.com/1038612/136071421-efc4f493-4c72-4d8e-843c-b7d7bb2db2f8.png)

by the following code:

```python
    else:
        vector3=[100,100,100]
        return vector3
```

**Comment by breakthewall** [comment]
Ok thank you Pablo, that fixed the issue.
I just made a pull request.
